// =====================================================================
// Turnstile Service
// =====================================================================
// Handles server-side verification of Cloudflare Turnstile tokens
// Implements environment-aware bypass for local development

/**
 * Service to verify bot protection tokens
 * Requirements: Cloudflare Turnstile integration, NODE_ENV bypass logic
 */
export class TurnstileService {
  private static readonly VERIFY_URL = 'https://challenges.cloudflare.com/turnstile/v0/siteverify';
  private static readonly SECRET_KEY = process.env.CLOUDFLARE_TURNSTILE_SECRET_KEY;

  /**
   * Verifies the turnstile token with Cloudflare
   * @param token - Token generated by the client-side widget
   * @returns true if verification success or in development mode
   */
  static async verifyToken(token?: string): Promise<{ success: boolean; message?: string }> {
    // 1. Bypass check: Always succeed in development for smooth testing
    if (process.env.NODE_ENV === 'development') {
      console.info('🛡️ [TurnstileService] Development mode: Bypassing verification');
      return { success: true };
    }

    // 2. Configuration check: If secret is missing in prod, fail for security
    if (!this.SECRET_KEY && process.env.NODE_ENV === 'production') {
      console.error('❌ [TurnstileService] Missing CLOUDFLARE_TURNSTILE_SECRET_KEY in production');
      return { success: false, message: 'Bot protection is currently misconfigured' };
    }

    // 3. Token check: Fail if no token provided in strictly enforced environment
    if (!token) {
      return { success: false, message: 'Please complete the bot protection check' };
    }

    try {
      // 4. Verification request to Cloudflare
      const response = await fetch(this.VERIFY_URL, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/x-www-form-urlencoded',
        },
        body: `secret=${encodeURIComponent(this.SECRET_KEY || '')}&response=${encodeURIComponent(token)}`,
      });

      const data = await response.json();

      if (!data.success) {
        console.warn('⚠️ [TurnstileService] Verification failed:', data['error-codes']);
        return { 
          success: false, 
          message: 'Bot protection check failed. Please try again.' 
        };
      }

      return { success: true };
    } catch (error) {
      console.error('❌ [TurnstileService] Network error during verification:', error);
      return { 
        success: false, 
        message: 'Unable to reach bot protection service' 
      };
    }
  }
}
