-- =====================================================================
-- Migration: Create Roles System with JWT Hooks
-- =====================================================================
-- Description: Implements a zero-lookup RBAC system using Supabase's
--              custom JWT access token hooks. User roles are stamped
--              directly into JWT claims at authentication time.
--
-- Deployment Workflow:
--   1. Apply migration: npx supabase db push
--   2. Enable hook in Dashboard: Authentication → Hooks → Custom Access Token
--      Select function: public.custom_access_token_hook
--   3. Regenerate types: npx supabase gen types typescript --project-id euhfhbpcqsfkfhmyvrzw > lib/supabase/database.types.ts
--   4. Verify hook: Create test user, authenticate, decode JWT for 'user_role' claim
--
-- Rollback Instructions:
--   - DROP TRIGGER on_auth_user_created ON auth.users;
--   - DROP TRIGGER on_role_change ON public.user_roles;
--   - DROP FUNCTION public.custom_access_token_hook(jsonb);
--   - DROP FUNCTION public.handle_new_user_role();
--   - DROP FUNCTION public.log_role_changes();
--   - DROP TABLE public.role_audit_log;
--   - DROP TABLE public.user_roles;
--   - DROP TYPE public.app_role;
--
-- Security Model:
--   - user_roles table: Locked down, only supabase_auth_admin has access
--   - RLS policies: Admin role required for mutations, users can view own role
--   - JWT hook: Runs with SECURITY DEFINER, defaults to 'user' on errors
-- =====================================================================

-- =====================================================================
-- SECTION 1: Create app_role enum type
-- =====================================================================
-- Defines the three valid role values at the database level
-- Ensures type safety and prevents invalid role assignments

DO $$ BEGIN
  CREATE TYPE public.app_role AS ENUM ('user', 'moderator', 'admin');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- =====================================================================
-- SECTION 2: Create user_roles table
-- =====================================================================
-- Stores role assignments for users
-- One role per user (enforced by unique constraint on user_id)

CREATE TABLE IF NOT EXISTS public.user_roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  role public.app_role DEFAULT 'user'::public.app_role NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- =====================================================================
-- SECTION 3: Create indexes for performance
-- =====================================================================
-- Optimizes role lookups and filtering operations

CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles(user_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_role ON public.user_roles(role);

-- =====================================================================
-- SECTION 4: Revoke all public permissions
-- =====================================================================
-- Implements "Do Not Trust The Client" paradigm
-- Only supabase_auth_admin can directly access this table

REVOKE ALL ON public.user_roles FROM public;
REVOKE ALL ON public.user_roles FROM anon;
REVOKE ALL ON public.user_roles FROM authenticated;

-- Grant full access to supabase_auth_admin (used by JWT hook)
GRANT ALL ON public.user_roles TO supabase_auth_admin;


-- =====================================================================
-- SECTION 5: Create custom_access_token_hook function
-- =====================================================================
-- This function is triggered by Supabase Auth during authentication
-- It stamps the user's role directly into the JWT claims
-- Zero database lookups required for subsequent role checks

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event jsonb)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  claims jsonb;
  user_role public.app_role;
BEGIN
  -- Extract claims from authentication event
  claims := event->'claims';
  
  -- Fetch user role from secure table
  -- This is the ONLY database lookup for role checking
  SELECT role INTO user_role 
  FROM public.user_roles 
  WHERE user_id = (event->>'user_id')::uuid;
  
  -- Inject role into JWT claims under 'user_role' key
  IF user_role IS NOT NULL THEN
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role::text));
  ELSE
    -- Default to 'user' if no role found (safety fallback)
    claims := jsonb_set(claims, '{user_role}', '"user"');
  END IF;
  
  -- Return modified event with updated claims
  event := jsonb_set(event, '{claims}', claims);
  
  RETURN event;
EXCEPTION
  WHEN OTHERS THEN
    -- Critical: On error, default to 'user' role to prevent auth failures
    -- Log error for debugging but don't block authentication
    RAISE WARNING 'Error in custom_access_token_hook for user %: %', 
      event->>'user_id', SQLERRM;
    claims := jsonb_set(claims, '{user_role}', '"user"');
    event := jsonb_set(event, '{claims}', claims);
    RETURN event;
END;
$$;

-- Lock down function execution
REVOKE ALL ON FUNCTION public.custom_access_token_hook(jsonb) FROM public;
REVOKE ALL ON FUNCTION public.custom_access_token_hook(jsonb) FROM anon;
REVOKE ALL ON FUNCTION public.custom_access_token_hook(jsonb) FROM authenticated;

-- Grant execute permission only to supabase_auth_admin
GRANT EXECUTE ON FUNCTION public.custom_access_token_hook(jsonb) TO supabase_auth_admin;

-- Add function comment for documentation
COMMENT ON FUNCTION public.custom_access_token_hook(jsonb) IS 
'Custom JWT access token hook that stamps user roles into authentication tokens. Must be enabled in Supabase Dashboard: Authentication → Hooks → Custom Access Token.';


-- =====================================================================
-- SECTION 6: Create role_audit_log table
-- =====================================================================
-- Maintains complete audit trail of all role changes
-- Critical for security compliance and troubleshooting

CREATE TABLE IF NOT EXISTS public.role_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  old_role public.app_role,
  new_role public.app_role NOT NULL,
  changed_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  changed_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create indexes for efficient audit log queries
CREATE INDEX IF NOT EXISTS idx_role_audit_user_id ON public.role_audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_role_audit_changed_at ON public.role_audit_log(changed_at DESC);

-- =====================================================================
-- SECTION 7: Create log_role_changes trigger function
-- =====================================================================
-- Automatically logs all role changes to audit table
-- Captures INSERT and UPDATE operations with actor information

CREATE OR REPLACE FUNCTION public.log_role_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Log UPDATE operations when role actually changes
  IF TG_OP = 'UPDATE' AND OLD.role IS DISTINCT FROM NEW.role THEN
    INSERT INTO public.role_audit_log (user_id, old_role, new_role, changed_by)
    VALUES (NEW.user_id, OLD.role, NEW.role, auth.uid());
  
  -- Log INSERT operations (new role assignments)
  ELSIF TG_OP = 'INSERT' THEN
    INSERT INTO public.role_audit_log (user_id, old_role, new_role, changed_by)
    VALUES (NEW.user_id, NULL, NEW.role, auth.uid());
  END IF;
  
  RETURN NEW;
END;
$$;

-- Attach trigger to user_roles table
DROP TRIGGER IF EXISTS on_role_change ON public.user_roles;
CREATE TRIGGER on_role_change
  AFTER INSERT OR UPDATE ON public.user_roles
  FOR EACH ROW
  EXECUTE FUNCTION public.log_role_changes();

COMMENT ON FUNCTION public.log_role_changes() IS 
'Trigger function that automatically logs all role changes to role_audit_log table for security compliance.';


-- =====================================================================
-- SECTION 8: Create auto-role assignment trigger for new users
-- =====================================================================
-- Automatically assigns 'user' role to new registrations
-- Ensures all authenticated users have a valid role in the system

CREATE OR REPLACE FUNCTION public.handle_new_user_role()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Insert default 'user' role for new user
  INSERT INTO public.user_roles (user_id, role)
  VALUES (NEW.id, 'user');
  
  RETURN NEW;
EXCEPTION
  WHEN OTHERS THEN
    -- Critical: Log error but don't fail user creation
    -- User will get default 'user' role from JWT hook fallback
    RAISE WARNING 'Failed to create default role for user %: %', NEW.id, SQLERRM;
    RETURN NEW;
END;
$$;

-- Attach trigger to auth.users table
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user_role();

COMMENT ON FUNCTION public.handle_new_user_role() IS 
'Trigger function that automatically assigns default "user" role to new user registrations.';


-- =====================================================================
-- SECTION 9: Enable Row Level Security
-- =====================================================================
-- Implements defense-in-depth security model
-- RLS policies enforce role-based access control at database level

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_audit_log ENABLE ROW LEVEL SECURITY;

-- =====================================================================
-- SECTION 10: RLS Policies for user_roles table
-- =====================================================================

-- Policy: Admins can manage all user roles
-- Extracts 'user_role' claim from JWT and checks for 'admin' value
DROP POLICY IF EXISTS "Admins can manage user roles" ON public.user_roles;
CREATE POLICY "Admins can manage user roles"
ON public.user_roles
FOR ALL
USING ((auth.jwt() ->> 'user_role')::text = 'admin')
WITH CHECK ((auth.jwt() ->> 'user_role')::text = 'admin');

-- Policy: Users can view their own role
-- Allows users to see their own role assignment
DROP POLICY IF EXISTS "Users can view their own role" ON public.user_roles;
CREATE POLICY "Users can view their own role"
ON public.user_roles
FOR SELECT
USING (auth.uid() = user_id);

-- =====================================================================
-- SECTION 11: RLS Policies for role_audit_log table
-- =====================================================================

-- Policy: Admins can view all audit logs
DROP POLICY IF EXISTS "Admins can view audit logs" ON public.role_audit_log;
CREATE POLICY "Admins can view audit logs"
ON public.role_audit_log
FOR SELECT
USING ((auth.jwt() ->> 'user_role')::text = 'admin');

-- Policy: Users can view their own audit log
DROP POLICY IF EXISTS "Users can view their own audit log" ON public.role_audit_log;
CREATE POLICY "Users can view their own audit log"
ON public.role_audit_log
FOR SELECT
USING (auth.uid() = user_id);

-- =====================================================================
-- SECTION 12: Example RLS Patterns for Other Tables
-- =====================================================================
-- These examples demonstrate how to use JWT role claims in your own tables
-- Copy and adapt these patterns for role-based access control

-- Example 1: Admin-only operations
-- Use case: System configuration tables, sensitive data
/*
CREATE POLICY "Admin only access"
ON public.your_table
FOR ALL
USING ((auth.jwt() ->> 'user_role')::text = 'admin')
WITH CHECK ((auth.jwt() ->> 'user_role')::text = 'admin');
*/

-- Example 2: Moderator or Admin access
-- Use case: Content moderation, user management
/*
CREATE POLICY "Moderators can manage content"
ON public.forum_posts
FOR DELETE
USING ((auth.jwt() ->> 'user_role')::text IN ('moderator', 'admin'));
*/

-- Example 3: Owner or Admin access
-- Use case: User-owned resources with admin override
/*
CREATE POLICY "Users can update own profile"
ON public.profiles
FOR UPDATE
USING (
  auth.uid() = user_id 
  OR (auth.jwt() ->> 'user_role')::text = 'admin'
)
WITH CHECK (
  auth.uid() = user_id 
  OR (auth.jwt() ->> 'user_role')::text = 'admin'
);
*/

-- Example 4: Role-based read access with ownership
-- Use case: Private content visible to owner or moderators
/*
CREATE POLICY "View own or moderate"
ON public.user_content
FOR SELECT
USING (
  auth.uid() = user_id 
  OR (auth.jwt() ->> 'user_role')::text IN ('moderator', 'admin')
);
*/

-- Example 5: Hierarchical permissions
-- Use case: Different operations for different roles
/*
CREATE POLICY "Role-based operations"
ON public.cosplay_groups
FOR ALL
USING (
  CASE 
    WHEN (auth.jwt() ->> 'user_role')::text = 'admin' THEN true
    WHEN (auth.jwt() ->> 'user_role')::text = 'moderator' THEN TG_OP IN ('SELECT', 'UPDATE')
    WHEN auth.uid() = owner_id THEN true
    ELSE false
  END
);
*/


-- =====================================================================
-- SECTION 13: Verification Queries
-- =====================================================================
-- Run these queries after deployment to verify the system is working

-- Verify enum type exists
/*
SELECT enumlabel 
FROM pg_enum 
WHERE enumtypid = 'public.app_role'::regtype 
ORDER BY enumsortorder;
-- Expected: user, moderator, admin
*/

-- Verify tables exist with correct structure
/*
SELECT table_name, column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' 
  AND table_name IN ('user_roles', 'role_audit_log')
ORDER BY table_name, ordinal_position;
*/

-- Verify indexes exist
/*
SELECT indexname, tablename 
FROM pg_indexes 
WHERE schemaname = 'public' 
  AND tablename IN ('user_roles', 'role_audit_log');
-- Expected: idx_user_roles_user_id, idx_user_roles_role, idx_role_audit_user_id, idx_role_audit_changed_at
*/

-- Verify RLS is enabled
/*
SELECT tablename, rowsecurity 
FROM pg_tables 
WHERE schemaname = 'public' 
  AND tablename IN ('user_roles', 'role_audit_log');
-- Expected: Both should have rowsecurity = true
*/

-- Verify RLS policies exist
/*
SELECT schemaname, tablename, policyname, permissive, roles, cmd, qual
FROM pg_policies
WHERE schemaname = 'public'
  AND tablename IN ('user_roles', 'role_audit_log');
-- Expected: 4 policies total (2 per table)
*/

-- Verify functions exist
/*
SELECT routine_name, routine_type, security_type
FROM information_schema.routines
WHERE routine_schema = 'public'
  AND routine_name IN ('custom_access_token_hook', 'handle_new_user_role', 'log_role_changes');
-- Expected: All 3 functions with security_type = DEFINER
*/

-- Verify triggers exist
/*
SELECT trigger_name, event_object_table, action_timing, event_manipulation
FROM information_schema.triggers
WHERE trigger_schema = 'public'
  AND trigger_name IN ('on_auth_user_created', 'on_role_change');
-- Expected: on_auth_user_created on auth.users, on_role_change on user_roles
*/

-- Test JWT hook manually (requires test user)
/*
SELECT public.custom_access_token_hook(
  jsonb_build_object(
    'user_id', 'YOUR_TEST_USER_UUID',
    'claims', jsonb_build_object()
  )
);
-- Expected: Returns event with 'user_role' in claims
*/

-- Verify permissions are locked down
/*
SELECT grantee, privilege_type 
FROM information_schema.table_privileges 
WHERE table_schema = 'public' 
  AND table_name = 'user_roles';
-- Expected: Only supabase_auth_admin should have privileges
*/

-- =====================================================================
-- SECTION 14: Post-Deployment Checklist
-- =====================================================================
-- 
-- [ ] 1. Migration applied successfully: npx supabase db push
-- [ ] 2. No errors in migration output
-- [ ] 3. All verification queries return expected results
-- [ ] 4. JWT hook enabled in Supabase Dashboard:
--        Navigation: Dashboard → Authentication → Hooks → Custom Access Token
--        Function: public.custom_access_token_hook
-- [ ] 5. TypeScript types regenerated:
--        npx supabase gen types typescript --project-id euhfhbpcqsfkfhmyvrzw > lib/supabase/database.types.ts
-- [ ] 6. Test user created and authenticated
-- [ ] 7. JWT decoded and 'user_role' claim verified
-- [ ] 8. Role assignment tested through admin interface
-- [ ] 9. RLS policies tested (non-admin cannot modify roles)
-- [ ] 10. Audit log verified (role changes are logged)
--
-- =====================================================================
-- END OF MIGRATION
-- =====================================================================
